services:
  tethterchand-mongo:
    image: mongo:8.0
    container_name: tetherchand-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - tetherchand-network

  tethterchand-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tetherchand-app
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://tetherchand-mongo:27017/tetherchand
      - WALLEX_API_KEY=${WALLEX_API_KEY}
      - NOBITEX_TOKEN=${NOBITEX_TOKEN}
      - ABAN_TOKEN=${ABAN_TOKEN}
      - FETCH_INTERVAL=${FETCH_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - tethterchand-mongo
    ports:
      - "3000:3000"
    entrypoint: tail -f /dev/null
    volumes:
      - ./app:/app
    networks:
      - tetherchand-network

volumes:
  mongo-data:


networks:
  tetherchand-network:
    driver: bridge
