services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tetherchand-app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://tetherchand-mongo/tetherchand
      - WALLEX_API_KEY=${WALLEX_API_KEY}
      - NOBITEX_TOKEN=${NOBITEX_TOKEN}
      - ABAN_TOKEN=${ABAN_TOKEN}
      - FETCH_INTERVAL=${FETCH_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - tetherchand-network
      
  mongo:
    image: mongo:8.0
    container_name: tetherchand-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - tetherchand-network

  nginx:
    image: nginx:latest
    container_name: tetherchand-nginx
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/cert-local:/etc/nginx/certs:ro
    networks:
      - tetherchand-network

volumes:
  mongo-data:


networks:
  tetherchand-network:
    driver: bridge
