services:
  tetherchand-mongo:
    image: mongo:8.0
    container_name: tetherchand-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - tetherchand-network

  tetherchand-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tetherchand-app
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://tetherchand-mongo:27017/tetherchand
      - WALLEX_API_KEY=${WALLEX_API_KEY}
      - NOBITEX_TOKEN=${NOBITEX_TOKEN}
      - ABAN_TOKEN=${ABAN_TOKEN}
      - FETCH_INTERVAL=${FETCH_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
<<<<<<< HEAD
      - tetherchand-mongo
    ports:
      - 3000:3000
    command: tail -f /dev/null
    networks:
      - tetherchand-network

  tetherchand-mongo-express:
    container_name: tetherchand-mongo-express
    depends_on:
      - tetherchand-mongo
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: tetherchand-mongo
=======
      - tethterchand-mongo
>>>>>>> 8403b42613cbbfdd02bdae6ff3aff84b46a60de3
    ports:
      - "3000:3000"
    entrypoint: tail -f /dev/null
    volumes:
      - ./app:/app
    networks:
      - tetherchand-network

volumes:
  mongo-data:


networks:
  tetherchand-network:
    driver: bridge
